DROP TABLE IF EXISTS concert_cache CASCADE;
DROP TABLE IF EXISTS artist_resolutions CASCADE;
DROP TABLE IF EXISTS affinity_profiles CASCADE;
DROP TABLE IF EXISTS user_locations CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
