#!/usr/bin/env bash
# Render /opt/concertfinder/.env from SSM Parameter Store. Run on the instance
# by the deploy workflow, before `docker compose up`.
#
# Why the instance fetches instead of being handed values: SSM send-command
# retains its parameters for ~30 days, readable by anyone with SSM access, so
# pushing a secret through a command leaks it. Here the command names only a
# path; the values travel over the instance role. Nothing secret appears in
# command history, CloudTrail redacts SecureString values, and updating a
# credential no longer needs a shell on the box.
#
# Every parameter under /concertfinder/ becomes one KEY=value line. Adding a
# config value is a Terraform change, not a change here.
set -euo pipefail

PARAM_PATH=${PARAM_PATH:-/concertfinder}
ENV_FILE=${ENV_FILE:-/opt/concertfinder/.env}
OWNER=${OWNER:-concertfinder}
# useradd -m creates a matching group, so these are the same name on the
# instance. Split so the script can be exercised somewhere they differ.
GROUP=${GROUP:-$OWNER}
PLACEHOLDER=REPLACE_ME

fail() {
    printf '\033[31mRENDER FAILED\033[0m: %s\n' "$1" >&2
    exit 1
}

# The instance profile supplies credentials, but not a region.
if [ -z "${AWS_REGION:-}" ]; then
    token=$(curl -sS -m 5 -X PUT http://169.254.169.254/latest/api/token \
        -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' 2>/dev/null) || true
    AWS_REGION=$(curl -sS -m 5 -H "X-aws-ec2-metadata-token: $token" \
        http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null) || true
    [ -n "$AWS_REGION" ] || fail "could not determine AWS region (set AWS_REGION)"
    export AWS_REGION
fi

# --with-decryption covers SecureString. The CLI paginates this call itself.
raw=$(aws ssm get-parameters-by-path \
    --path "$PARAM_PATH" \
    --with-decryption \
    --query 'Parameters[].[Name,Value]' \
    --output text) || fail "could not read $PARAM_PATH (check the instance role)"

[ -n "$raw" ] || fail "no parameters found under $PARAM_PATH"

# Write to a temp file and install atomically. A half-written .env is worse
# than a stale one: docker compose would load it and the container would come
# up with a truncated config, which config.Validate reports as a missing
# variable rather than as a broken render.
tmp=$(mktemp /tmp/cf-env.XXXXXX)
chmod 600 "$tmp"
trap 'rm -f "$tmp"' EXIT

{
    echo "# Generated by scripts/render-env.sh from SSM $PARAM_PATH"
    echo "# Do not edit by hand -- the next deploy overwrites it."
    echo "# Change a value with: aws ssm put-parameter --name $PARAM_PATH/<KEY> \\"
    echo "#   --type SecureString --value file://value.txt --overwrite"
    echo
} > "$tmp"

missing=()
count=0
while IFS=$'\t' read -r name value; do
    [ -n "$name" ] || continue
    key=${name##*/}
    if [ "$value" = "$PLACEHOLDER" ]; then
        missing+=("$key")
        continue
    fi
    # Single-quote the value. This file has two consumers with two different
    # parsers: docker compose reads it as an env_file, and scripts/backup-db.sh
    # does `set -a; . "$ENV_FILE"` -- i.e. it hands it to bash. Written bare, a
    # value holding a space, a `$`, a backtick or a `;` is fine for compose and
    # is a syntax error or a command substitution for bash, so the failure is
    # invisible in the worst way: the app stays perfectly healthy and only the
    # nightly backup, which nobody watches, dies. Compose strips surrounding
    # single quotes, so quoting satisfies both.
    #
    # A value containing a single quote itself is REFUSED rather than escaped,
    # because no single encoding satisfies both parsers -- verified against
    # `docker compose config`, not assumed:
    #
    #   - The shell's '\'' idiom (close, escape, reopen) is a parse error for
    #     compose: "unexpected character \" in variable name".
    #   - Double-quoting with backslash escapes agrees with bash on \, " and $,
    #     and diverges on the backtick -- compose keeps the backslash literal
    #     while bash strips it and runs the command substitution. That is the
    #     dangerous direction to be wrong in.
    #
    # So single quotes are the encoding, and the one value they cannot carry
    # fails here, by name, before anything is written -- rather than on the
    # instance mid-deploy, or silently in the backup at 3am.
    #
    # APNS_P8_KEY's `\n` sequences survive unchanged: they are two literal
    # characters by the time they get here (set-secrets.sh escapes the PEM
    # because this read loop and compose's env_file are both line-oriented),
    # single quotes keep them literal, and push.parseP8 unescapes them before
    # pem.Decode.
    case "$value" in
        *"'"*)
            # The value is never echoed: these are secrets.
            echo "ERROR: value of $key contains a single quote, which cannot be" >&2
            echo "  encoded safely for both docker compose and 'set -a; . \$ENV_FILE'." >&2
            echo "  Re-issue that secret without one and re-run put-parameter." >&2
            exit 1
            ;;
    esac
    printf "%s='%s'\n" "$key" "$value" >> "$tmp"
    count=$((count + 1))
done <<< "$raw"

# A parameter still holding the sentinel means nobody ever set it. Failing here
# names the parameter; letting it through means the container boots with the
# literal string REPLACE_ME and config.Validate complains about a malformed
# value instead, pointing at the format rather than at the empty slot.
if [ ${#missing[@]} -gt 0 ]; then
    fail "these parameters are still unset: ${missing[*]}
    set each with: aws ssm put-parameter --name $PARAM_PATH/<KEY> --type SecureString --value file://value.txt --overwrite"
fi

[ "$count" -gt 0 ] || fail "rendered no variables"

install -o "$OWNER" -g "$GROUP" -m 600 "$tmp" "$ENV_FILE"
printf 'rendered %s (%d variables) from %s\n' "$ENV_FILE" "$count" "$PARAM_PATH"
