#!/usr/bin/env bash
# Timed restore drill against a nightly dump in S3. Run from your laptop with
# admin credentials — the instance role can PutObject and nothing else, which
# is deliberate (infra/backups.tf), so a restore cannot be driven from the box.
#
# Two questions this answers, and they are different:
#
#   1. Is there a restore point at all? `--check` alone answers that in a few
#      seconds. It is not a rhetorical question: the .env is sourced by
#      backup-db.sh, and an unquoted value with a space in it (APNS_P8_KEY, for
#      most of this project's life) makes that source fail — so the nightly
#      timer has been capable of failing every night while everything else
#      looked healthy.
#
#   2. How long does a restore take, and does the restored data actually have
#      the rows in it? That is the RTO, and it is unknown until measured. A
#      dump that restores an empty schema exits 0 and looks exactly like a
#      successful drill, which is why the row assertions below are the point of
#      the script rather than a flourish at the end.
#
# Usage:
#   scripts/restore-drill.sh --check
#   scripts/restore-drill.sh 'postgres://…scratch-branch…?sslmode=require'
#   scripts/restore-drill.sh --key pg/concertfinder-2026-08-30.dump '<url>'
#
# The target must be a SCRATCH database — a Neon branch made for the drill
# (`neon branches create`), not the production branch. The restore is
# --clean --if-exists, so it drops what it finds. The guard below refuses a
# target that already holds users, which is what makes a mispasted production
# URL a refusal rather than an outage; --force is there for the second drill
# into the same scratch branch, and for nothing else.
set -euo pipefail

# Same image and same reason as scripts/backup-db.sh: pg_restore must be at
# least the server's major version, the archive is custom-format, and pinning
# means a Neon major bump fails loudly here rather than silently producing an
# unusable drill. Keep this in step with backup-db.sh's PG_IMAGE.
PG_IMAGE=${PG_IMAGE:-postgres:18-alpine}

# How old the newest dump may be before this is a failure rather than a drill.
# Two days, not one: a drill run at 02:00 UTC is legitimately looking at
# yesterday's 03:00 dump.
MAX_AGE_DAYS=${MAX_AGE_DAYS:-2}

# The tables that do not rebuild themselves. Everything else in the schema —
# concerts, the caches, the snapshots — is regenerated by the next scan, so a
# restore that brought those back and lost these would still be a total loss.
IRREPLACEABLE=(users user_saved_concerts user_subscribed_artists user_locations)

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RESET=$'\033[0m'

fail() { printf '%sDRILL FAILED%s: %s\n' "$RED" "$RESET" "$1" >&2; exit 1; }
info() { printf '  %s\n' "$1"; }
step() { printf '\n%s==> %s%s\n' "$GREEN" "$1" "$RESET"; }

check_only=false
force=false
key=""
target=""

while [ $# -gt 0 ]; do
    case "$1" in
        --check) check_only=true; shift ;;
        --force) force=true; shift ;;
        --key) key=${2:-}; [ -n "$key" ] || fail "--key needs a value"; shift 2 ;;
        -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*) fail "unknown flag: $1" ;;
        *) target=$1; shift ;;
    esac
done

command -v aws >/dev/null || fail "aws CLI not on PATH"
command -v docker >/dev/null || fail "docker not on PATH (pg_restore runs in $PG_IMAGE)"

# Derived rather than passed, and derived the same way infra/backups.tf names
# it. A drill against the wrong bucket reports a missing backup for a backup
# that exists, which is the most alarming way to be wrong.
if [ -z "${BACKUP_S3_BUCKET:-}" ]; then
    account=$(aws sts get-caller-identity --query Account --output text) ||
        fail "aws sts get-caller-identity failed — no usable credentials"
    BACKUP_S3_BUCKET="concertfinder-backups-${account}"
fi
info "bucket: s3://${BACKUP_S3_BUCKET}"

step "Finding the newest dump"
# --output text over a --query that sorts by LastModified. `aws s3 ls` sorts
# lexicographically by key, which happens to agree with date order today and
# stops agreeing the moment a key is ever named anything else.
newest=$(aws s3api list-objects-v2 \
    --bucket "$BACKUP_S3_BUCKET" --prefix pg/ \
    --query 'sort_by(Contents, &LastModified)[-1].[Key,LastModified,Size]' \
    --output text 2>/dev/null) || fail "cannot list s3://${BACKUP_S3_BUCKET}/pg/"

[ -n "$newest" ] && [ "$newest" != "None" ] ||
    fail "no objects under s3://${BACKUP_S3_BUCKET}/pg/ at all. There is no restore point. Check the timer on the instance: systemctl list-timers concertfinder-backup"

newest_key=$(printf '%s' "$newest" | cut -f1)
newest_at=$(printf '%s' "$newest" | cut -f2)
newest_size=$(printf '%s' "$newest" | cut -f3)

# GNU date and BSD date disagree on everything except -u +%s, so the epoch is
# computed by python3 (present on macOS and on every runner) rather than by
# guessing which date this laptop has.
age_days=$(python3 -c '
import sys, datetime
ts = sys.argv[1].replace("Z", "+00:00")
d = datetime.datetime.fromisoformat(ts)
now = datetime.datetime.now(datetime.timezone.utc)
print(f"{(now - d).total_seconds() / 86400:.1f}")
' "$newest_at")

info "newest: $newest_key"
info "taken:  $newest_at (${age_days} days ago)"
info "size:   ${newest_size} bytes"

# Float comparison, so awk rather than [ -gt ]: age_days has a decimal in it and
# a shell integer test on "1.4" is a syntax error, not a comparison.
if awk -v a="$age_days" -v m="$MAX_AGE_DAYS" 'BEGIN { exit !(a > m) }'; then
    fail "newest dump is ${age_days} days old (limit ${MAX_AGE_DAYS}). The nightly backup is not running. Look for a sourcing failure in the .env before anything else: journalctl -u concertfinder-backup -n 50"
fi

# A dump that shrinks by an order of magnitude is a dump of a database that
# lost something, and it is the failure that a freshness check waves through.
# Reported rather than enforced: real growth and a real loss look the same from
# here, and only a human knows which this is.
previous=$(aws s3api list-objects-v2 \
    --bucket "$BACKUP_S3_BUCKET" --prefix pg/ \
    --query 'sort_by(Contents, &LastModified)[-2].Size' \
    --output text 2>/dev/null || echo None)
if [ "$previous" != "None" ] && [ -n "$previous" ] && [ "$previous" -gt 0 ] 2>/dev/null; then
    pct=$(( newest_size * 100 / previous ))
    info "size vs previous dump: ${pct}%"
    [ "$pct" -ge 50 ] ||
        printf '%s  warning: newest dump is less than half the previous one%s\n' "$YELLOW" "$RESET"
fi

if [ "$check_only" = true ]; then
    printf '\n%sBackup present and fresh.%s Restore not attempted (--check).\n' "$GREEN" "$RESET"
    exit 0
fi

[ -n "$target" ] ||
    fail "no target database URL. Pass a SCRATCH Neon branch URL, or --check to only verify a restore point exists."

[ -n "$key" ] || key=$newest_key

work=$(mktemp -d /tmp/concertfinder-drill.XXXXXX)
trap 'rm -rf "$work"' EXIT
dump="$work/dump"

step "Downloading $key"
aws s3 cp "s3://${BACKUP_S3_BUCKET}/${key}" "$dump" --only-show-errors ||
    fail "download failed"

# Same check backup-db.sh runs before uploading, repeated here because this is
# the run that proves the object in S3 — not the temp file on the instance — is
# readable. Bind-mounted, never piped: a custom-format archive is read by
# seeking, and pg_restore against a pipe fails with "did not find magic string
# in file header" no matter how good the dump is.
step "Verifying the archive"
docker run --rm -v "$dump:/dump:ro" "$PG_IMAGE" pg_restore --list /dump >/dev/null ||
    fail "pg_restore --list rejected the archive. This object is not a usable backup."
info "table of contents reads cleanly"

psql_q() {
    docker run --rm -i -e TARGET_URL "$PG_IMAGE" \
        psql --dbname="$TARGET_URL" -tAc "$1" 2>/dev/null
}
export TARGET_URL=$target

step "Checking the target is a scratch database"
target_host=$(printf '%s' "$target" | sed -E 's|^[a-z+]+://[^@]*@||; s|[:/?].*$||')
info "target host: $target_host"

existing=$(psql_q "SELECT count(*) FROM users" || true)
if [ -n "$existing" ] && [ "$existing" != "0" ]; then
    [ "$force" = true ] ||
        fail "target already has ${existing} rows in users. This drill restores with --clean --if-exists and would drop them. If this is really a scratch branch, re-run with --force; if you pasted the production URL, do not."
    printf '%s  --force given; restoring over %s existing users%s\n' "$YELLOW" "$existing" "$RESET"
fi

step "Restoring (this is the number the drill exists to produce)"
started=$(date -u +%s)
if ! docker run --rm -i -e TARGET_URL -v "$dump:/dump:ro" "$PG_IMAGE" \
        pg_restore --dbname="$TARGET_URL" --clean --if-exists --no-owner \
        --no-privileges /dump >"$work/restore.log" 2>&1; then
    tail -20 "$work/restore.log" | sed 's/^/    /' >&2
    fail "pg_restore exited non-zero — see the tail above"
fi
elapsed=$(( $(date -u +%s) - started ))

# pg_restore warns rather than fails on plenty of things that do not matter
# (dropping objects that were not there, extension ownership). Surfaced, not
# escalated: the row counts below are the actual verdict.
warnings=$(grep -ci 'warning' "$work/restore.log" || true)
[ "${warnings:-0}" -eq 0 ] || info "pg_restore emitted ${warnings} warnings (see below if the counts look wrong)"

step "Verifying the restored data"
missing=0
for t in "${IRREPLACEABLE[@]}"; do
    n=$(psql_q "SELECT count(*) FROM ${t}" || true)
    if [ -z "$n" ]; then
        printf '  %s%-26s table missing entirely%s\n' "$RED" "$t" "$RESET"
        missing=1
    else
        printf '  %-26s %s rows\n' "$t" "$n"
        # `users` is the only one that cannot legitimately be empty: a
        # deployment with no saves or no set locations is plausible, a
        # deployment with no accounts is a restore that restored nothing.
        if [ "$t" = users ] && [ "$n" = "0" ]; then
            printf '  %susers is empty — the restore produced a schema, not data%s\n' "$RED" "$RESET"
            missing=1
        fi
    fi
done
[ "$missing" -eq 0 ] || fail "the restored database is missing data that does not rebuild itself"

printf '\n%sDRILL PASSED%s\n' "$GREEN" "$RESET"
printf '  dump:          %s (%s)\n' "$key" "$newest_at"
printf '  restore time:  %dm %ds\n' $(( elapsed / 60 )) $(( elapsed % 60 ))
printf '\n  That restore time is the measured RTO for the data layer, and it excludes\n'
printf '  everything around it: noticing, deciding, making a branch, and pointing\n'
printf '  DATABASE_URL at it followed by a deploy. Record it in docs/aws-deploy.md\n'
printf '  and drop the scratch branch.\n'
