#!/usr/bin/env bash
# Timed restore drill against a nightly dump in S3. Run from your laptop with
# admin credentials — the instance role can PutObject and nothing else, which
# is deliberate (infra/backups.tf), so a restore cannot be driven from the box.
#
# Two questions this answers, and they are different:
#
#   1. Is there a restore point at all? `--check` alone answers that in a few
#      seconds. It is not a rhetorical question: the .env is sourced by
#      backup-db.sh, and an unquoted value with a space in it (APNS_P8_KEY, for
#      most of this project's life) makes that source fail — so the nightly
#      timer has been capable of failing every night while everything else
#      looked healthy.
#
#   2. How long does a restore take, and does the restored data actually have
#      the rows in it? That is the RTO, and it is unknown until measured. A
#      dump that restores an empty schema exits 0 and looks exactly like a
#      successful drill, which is why the row assertions below are the point of
#      the script rather than a flourish at the end.
#
# Usage:
#   scripts/restore-drill.sh --check
#   scripts/restore-drill.sh 'postgres://…scratch-branch…?sslmode=require'
#   scripts/restore-drill.sh --key pg/concertfinder-2026-08-30.dump '<url>'
#   scripts/restore-drill.sh --size-verdict 2078242 2071949 109323   # offline
#
# The target must be a SCRATCH database — a Neon branch made for the drill
# (`neon branches create`), not the production branch. The restore is
# --clean --if-exists, so it drops what it finds. The guard below refuses a
# target that already holds users, which is what makes a mispasted production
# URL a refusal rather than an outage; --force is there for the second drill
# into the same scratch branch, and for nothing else.
set -euo pipefail

# Same image and same reason as scripts/backup-db.sh: pg_restore must be at
# least the server's major version, the archive is custom-format, and pinning
# means a Neon major bump fails loudly here rather than silently producing an
# unusable drill. Keep this in step with backup-db.sh's PG_IMAGE.
PG_IMAGE=${PG_IMAGE:-postgres:18-alpine}

# How old the newest dump may be before this is a failure rather than a drill.
# Two days, not one: a drill run at 02:00 UTC is legitimately looking at
# yesterday's 03:00 dump.
MAX_AGE_DAYS=${MAX_AGE_DAYS:-2}

# The size guards, and they are two different instruments because the failure
# they exist for has two shapes.
#
# MIN_DUMP_BYTES is a level. It answers "is this a dump of a database at all",
# and the number is derived rather than picked: a --schema-only dump of this
# schema is 39,851 bytes (2026-09-14, 22 migrations), and the smallest dump
# ever taken of a real database here is 65,916 bytes (2026-08-22, two users and
# almost nothing else). The floor sits between them with room on both sides.
# Re-derive it the same way if the schema grows a lot:
#   pg_dump --format=custom --schema-only | wc -c
#
# MIN_BASELINE_PCT is a ratio, and BASELINE_DUMPS is what it is a ratio *to*.
# It used to be a day-over-day comparison, which is a derivative — and the
# failure it was meant to catch is a level, so it could only see the step on
# the night the step happened. On 2026-09-10 the nightly dump fell from
# 2,071,949 to 109,323 bytes; by 2026-09-14 each ~108 KB dump sat beside
# another ~108 KB dump and the check reported "99%" and passed, five nights
# into a payload it had never seen before. A median over a window remembers
# the old level for as long as the window is long. Ten days is chosen so a
# single anomalous night cannot move it and so a real step is still visible a
# week later; it is deliberately not a mean, which one 11 MB night would drag.
MIN_DUMP_BYTES=${MIN_DUMP_BYTES:-50000}
BASELINE_DUMPS=${BASELINE_DUMPS:-10}
MIN_BASELINE_PCT=${MIN_BASELINE_PCT:-50}

# The tables that do not rebuild themselves. Everything else in the schema —
# concerts, the caches, the snapshots — is regenerated by the next scan, so a
# restore that brought those back and lost these would still be a total loss.
IRREPLACEABLE=(users user_saved_concerts user_subscribed_artists user_locations)

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RESET=$'\033[0m'

fail() { printf '%sDRILL FAILED%s: %s\n' "$RED" "$RESET" "$1" >&2; exit 1; }
info() { printf '  %s\n' "$1"; }
step() { printf '\n%s==> %s%s\n' "$GREEN" "$1" "$RESET"; }

# Median of the integers passed. Integer arithmetic throughout, because these
# are byte counts and bash has no floats — an even-sized window averages its
# two middle values, which for byte counts loses at most half a byte.
median() {
    local sorted count lo hi
    count=$#
    sorted=$(printf '%s\n' "$@" | sort -n)
    if [ $(( count % 2 )) -eq 1 ]; then
        printf '%s' "$(printf '%s\n' "$sorted" | sed -n "$(( count / 2 + 1 ))p")"
    else
        lo=$(printf '%s\n' "$sorted" | sed -n "$(( count / 2 ))p")
        hi=$(printf '%s\n' "$sorted" | sed -n "$(( count / 2 + 1 ))p")
        printf '%s' $(( (lo + hi) / 2 ))
    fi
}

# The whole size judgement, and the reason it is a function taking a list of
# integers rather than a block inline in the S3 path: this is the part that
# was wrong, so it has to be exercisable with synthetic inputs and without
# credentials. scripts/check-deploy-config.sh calls it through --size-verdict.
#
# Arguments are dump sizes in chronological order, oldest first, and the LAST
# one is the dump being judged. Returns 0 if it passes both guards, 1 if
# either rejects it, printing which.
size_verdict() {
    local all newest baseline med pct n verdict=0

    [ $# -ge 1 ] || { printf '%ssize_verdict: no sizes given%s\n' "$RED" "$RESET" >&2; return 2; }

    # Every comparison below is integer arithmetic, and bash answers a
    # non-numeric operand with a syntax error on stderr and a non-zero status —
    # which under `set -e` would look like a rejected dump rather than a broken
    # call. Say which argument was wrong instead.
    for n in "$@"; do
        case "$n" in
            ''|*[!0-9]*) printf '%ssize_verdict: %s is not a byte count%s\n' "$RED" "$n" "$RESET" >&2; return 2 ;;
        esac
    done

    all="$*"
    newest=${all##* }
    baseline=${all% *}
    [ "$baseline" != "$all" ] || baseline=""

    # The window is the N dumps immediately before this one. `tail` rather than
    # a slice so that fewer than N available is simply a shorter window and not
    # an error: a bucket four days old still gets a baseline, just a weaker one.
    if [ -n "$baseline" ]; then
        baseline=$(printf '%s\n' $baseline | tail -n "$BASELINE_DUMPS" | tr '\n' ' ')
    fi

    if [ "$newest" -lt "$MIN_DUMP_BYTES" ]; then
        printf '%s  below the floor: %s bytes, and a dump of this database cannot legitimately be under %s.%s\n' \
            "$RED" "$newest" "$MIN_DUMP_BYTES" "$RESET"
        printf '  A schema-only dump is about 40 KB, so this is at or near "the schema restored and the data did not".\n'
        verdict=1
    fi

    if [ -n "$baseline" ]; then
        # shellcheck disable=SC2086
        med=$(median $baseline)
        if [ "${med:-0}" -gt 0 ]; then
            pct=$(( newest * 100 / med ))
            info "size vs median of the previous $(printf '%s\n' $baseline | wc -l | tr -d ' ') dumps: ${pct}% (median ${med} bytes)"
            if [ "$pct" -lt "$MIN_BASELINE_PCT" ]; then
                printf '%s  payload cliff: this dump is %s%% of the median of the window, floor is %s%%.%s\n' \
                    "$RED" "$pct" "$MIN_BASELINE_PCT" "$RESET"
                printf '  Something the database used to hold is not in this dump. Restore it into a\n'
                printf '  scratch branch and count rows before trusting it: scripts/restore-drill.sh <url>\n'
                verdict=1
            fi
        fi
    fi

    return $verdict
}

check_only=false
force=false
verdict_only=false
key=""
target=""
sizes=""

while [ $# -gt 0 ]; do
    case "$1" in
        --check) check_only=true; shift ;;
        --force) force=true; shift ;;
        --size-verdict) verdict_only=true; shift ;;
        --key) key=${2:-}; [ -n "$key" ] || fail "--key needs a value"; shift 2 ;;
        -h|--help) sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*) fail "unknown flag: $1" ;;
        *) if [ "$verdict_only" = true ]; then sizes="$sizes $1"; else target=$1; fi; shift ;;
    esac
done

# Deliberately before the aws and docker checks below: judging a list of
# integers needs neither, and a test that needed credentials would not be run.
if [ "$verdict_only" = true ]; then
    # The status is propagated rather than flattened to 1: size_verdict answers
    # 2 for "you called this wrong" and 1 for "this dump is wrong", and a test
    # harness that cannot tell those apart passes when it is itself broken.
    # shellcheck disable=SC2086
    size_verdict $sizes || exit $?
    printf '%sSIZE OK%s\n' "$GREEN" "$RESET"
    exit 0
fi

command -v aws >/dev/null || fail "aws CLI not on PATH"
command -v docker >/dev/null || fail "docker not on PATH (pg_restore runs in $PG_IMAGE)"

# Derived rather than passed, and derived the same way infra/backups.tf names
# it. A drill against the wrong bucket reports a missing backup for a backup
# that exists, which is the most alarming way to be wrong.
if [ -z "${BACKUP_S3_BUCKET:-}" ]; then
    account=$(aws sts get-caller-identity --query Account --output text) ||
        fail "aws sts get-caller-identity failed — no usable credentials"
    BACKUP_S3_BUCKET="concertfinder-backups-${account}"
fi
info "bucket: s3://${BACKUP_S3_BUCKET}"

step "Finding the newest dump"
# --output text over a --query that sorts by LastModified. `aws s3 ls` sorts
# lexicographically by key, which happens to agree with date order today and
# stops agreeing the moment a key is ever named anything else.
newest=$(aws s3api list-objects-v2 \
    --bucket "$BACKUP_S3_BUCKET" --prefix pg/ \
    --query 'sort_by(Contents, &LastModified)[-1].[Key,LastModified,Size]' \
    --output text 2>/dev/null) || fail "cannot list s3://${BACKUP_S3_BUCKET}/pg/"

[ -n "$newest" ] && [ "$newest" != "None" ] ||
    fail "no objects under s3://${BACKUP_S3_BUCKET}/pg/ at all. There is no restore point. Check the timer on the instance: systemctl list-timers concertfinder-backup"

newest_key=$(printf '%s' "$newest" | cut -f1)
newest_at=$(printf '%s' "$newest" | cut -f2)
newest_size=$(printf '%s' "$newest" | cut -f3)

# GNU date and BSD date disagree on everything except -u +%s, so the epoch is
# computed by python3 (present on macOS and on every runner) rather than by
# guessing which date this laptop has.
age_days=$(python3 -c '
import sys, datetime
ts = sys.argv[1].replace("Z", "+00:00")
d = datetime.datetime.fromisoformat(ts)
now = datetime.datetime.now(datetime.timezone.utc)
print(f"{(now - d).total_seconds() / 86400:.1f}")
' "$newest_at")

info "newest: $newest_key"
info "taken:  $newest_at (${age_days} days ago)"
info "size:   ${newest_size} bytes"

# Float comparison, so awk rather than [ -gt ]: age_days has a decimal in it and
# a shell integer test on "1.4" is a syntax error, not a comparison.
if awk -v a="$age_days" -v m="$MAX_AGE_DAYS" 'BEGIN { exit !(a > m) }'; then
    fail "newest dump is ${age_days} days old (limit ${MAX_AGE_DAYS}). The nightly backup is not running. Look for a sourcing failure in the .env before anything else: journalctl -u concertfinder-backup -n 50"
fi

# A dump that shrinks by an order of magnitude is a dump of a database that
# lost something, and it is the failure a freshness check waves through: the
# object is there, it is today's, and it is a fraction of what it should be.
#
# The window includes the newest dump as its last element, which is exactly
# size_verdict's contract. A JMESPath slice rather than two queries so the
# newest and its baseline come from one listing and cannot disagree.
history=$(aws s3api list-objects-v2 \
    --bucket "$BACKUP_S3_BUCKET" --prefix pg/ \
    --query "sort_by(Contents, &LastModified)[-$(( BASELINE_DUMPS + 1 )):].Size" \
    --output text 2>/dev/null | tr '\t' ' ') ||
    fail "cannot list the dump history in s3://${BACKUP_S3_BUCKET}/pg/. The newest object was readable a moment ago, so this is not a missing backup — but without the window there is no cliff guard, and passing on the floor alone is the failure this check exists to stop."

[ -n "$history" ] || history=$newest_size

# Enforced, not warned. It was a warning for as long as it was a day-over-day
# ratio, because at one day's remove a real loss and real growth are the same
# shape and only a human can tell them apart — but a step measured against a
# ten-day median is not ambiguous in that way, and a warning printed above the
# words "Backup present and fresh" is a warning nobody acts on.
# shellcheck disable=SC2086
size_verdict $history ||
    fail "the newest dump does not look like a dump of this database. See above. This is not a restore point until someone has restored it and counted rows."

if [ "$check_only" = true ]; then
    printf '\n%sBackup present and fresh.%s Restore not attempted (--check).\n' "$GREEN" "$RESET"
    exit 0
fi

[ -n "$target" ] ||
    fail "no target database URL. Pass a SCRATCH Neon branch URL, or --check to only verify a restore point exists."

[ -n "$key" ] || key=$newest_key

work=$(mktemp -d /tmp/concertfinder-drill.XXXXXX)
trap 'rm -rf "$work"' EXIT
dump="$work/dump"

step "Downloading $key"
aws s3 cp "s3://${BACKUP_S3_BUCKET}/${key}" "$dump" --only-show-errors ||
    fail "download failed"

# Same check backup-db.sh runs before uploading, repeated here because this is
# the run that proves the object in S3 — not the temp file on the instance — is
# readable. Bind-mounted, never piped: a custom-format archive is read by
# seeking, and pg_restore against a pipe fails with "did not find magic string
# in file header" no matter how good the dump is.
step "Verifying the archive"
docker run --rm -v "$dump:/dump:ro" "$PG_IMAGE" pg_restore --list /dump >/dev/null ||
    fail "pg_restore --list rejected the archive. This object is not a usable backup."
info "table of contents reads cleanly"

psql_q() {
    docker run --rm -i -e TARGET_URL "$PG_IMAGE" \
        psql --dbname="$TARGET_URL" -tAc "$1" 2>/dev/null
}
export TARGET_URL=$target

step "Checking the target is a scratch database"
target_host=$(printf '%s' "$target" | sed -E 's|^[a-z+]+://[^@]*@||; s|[:/?].*$||')
info "target host: $target_host"

existing=$(psql_q "SELECT count(*) FROM users" || true)
if [ -n "$existing" ] && [ "$existing" != "0" ]; then
    [ "$force" = true ] ||
        fail "target already has ${existing} rows in users. This drill restores with --clean --if-exists and would drop them. If this is really a scratch branch, re-run with --force; if you pasted the production URL, do not."
    printf '%s  --force given; restoring over %s existing users%s\n' "$YELLOW" "$existing" "$RESET"
fi

step "Restoring (this is the number the drill exists to produce)"
started=$(date -u +%s)
if ! docker run --rm -i -e TARGET_URL -v "$dump:/dump:ro" "$PG_IMAGE" \
        pg_restore --dbname="$TARGET_URL" --clean --if-exists --no-owner \
        --no-privileges /dump >"$work/restore.log" 2>&1; then
    tail -20 "$work/restore.log" | sed 's/^/    /' >&2
    fail "pg_restore exited non-zero — see the tail above"
fi
elapsed=$(( $(date -u +%s) - started ))

# pg_restore warns rather than fails on plenty of things that do not matter
# (dropping objects that were not there, extension ownership). Surfaced, not
# escalated: the row counts below are the actual verdict.
warnings=$(grep -ci 'warning' "$work/restore.log" || true)
[ "${warnings:-0}" -eq 0 ] || info "pg_restore emitted ${warnings} warnings (see below if the counts look wrong)"

step "Verifying the restored data"
missing=0
for t in "${IRREPLACEABLE[@]}"; do
    n=$(psql_q "SELECT count(*) FROM ${t}" || true)
    if [ -z "$n" ]; then
        printf '  %s%-26s table missing entirely%s\n' "$RED" "$t" "$RESET"
        missing=1
    else
        printf '  %-26s %s rows\n' "$t" "$n"
        # `users` is the only one that cannot legitimately be empty: a
        # deployment with no saves or no set locations is plausible, a
        # deployment with no accounts is a restore that restored nothing.
        if [ "$t" = users ] && [ "$n" = "0" ]; then
            printf '  %susers is empty — the restore produced a schema, not data%s\n' "$RED" "$RESET"
            missing=1
        fi
    fi
done
[ "$missing" -eq 0 ] || fail "the restored database is missing data that does not rebuild itself"

printf '\n%sDRILL PASSED%s\n' "$GREEN" "$RESET"
printf '  dump:          %s (%s)\n' "$key" "$newest_at"
printf '  restore time:  %dm %ds\n' $(( elapsed / 60 )) $(( elapsed % 60 ))
printf '\n  That restore time is the measured RTO for the data layer, and it excludes\n'
printf '  everything around it: noticing, deciding, making a branch, and pointing\n'
printf '  DATABASE_URL at it followed by a deploy. Record it in docs/aws-deploy.md\n'
printf '  and drop the scratch branch.\n'
